import type { Metadata } from 'next'
import { Atkinson_Hyperlegible,Poppins } from 'next/font/google'
import './globals.css'
import Footer from './(website)/components/layout/Footer/Footer';

const atkinsonHyperlegible = Atkinson_Hyperlegible({
  weight: ["400","700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--atkinsonHyperlegible"
});

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--poppins",
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${atkinsonHyperlegible.variable} ${poppins.variable} `}>
        

        {children}
        {/* <Footer /> */}
       
      </body>
    </html>
  )
}
